version: "3.9"
services:
  streamlit:
    build:
      context: ./streamlit
      dockerfile: ./Dockerfile
    networks:
      shared-nw:
    # volumes:
    #   - ./streamlit:/streamlit
    ports:
      - 8501:8501
    command: streamlit run /streamlit/app.py --browser.serverAddress="0.0.0.0" --server.port="8501"
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server-2019-express
    ports: 
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
    env_file:
      - sql-server-2019.env
    volumes:
      - ./DB/DATA:/var/opt/mssql/data
      - ./DB/LOG:/var/opt/mssql/log
      - ./DB/secrets:/var/opt/mssql/sec
  # nginx:
  #   build: ./nginx
  #   networks:
  #     shared-nw:
  #   ports:
  #     - 443:443
networks:
  shared-nw:
    driver: bridge
