version: "3.9"
services:
  streamlit:
    build:
      context: ./streamlit
      dockerfile: ./Dockerfile
    networks:
      shared-nw:
    # volumes:
    #   - ./streamlit:/streamlit
    ports:
      - 8501:8501
    command: streamlit run /streamlit/app.py --browser.serverAddress="0.0.0.0" --server.port="8501"
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=saPassword1234
      - MSSQL_PID=Express
      - MSSQL_LCID=1041
      - MSSQL_COLLATION=Japanese_CI_AS
    # volumes:
    #   - './docker/db/data:/var/opt/mssql/data'
    #   - './docker/db/log:/var/opt/mssql/log'
    #   - './docker/db/secrets:/var/opt/mssql/secrets'
  # nginx:
  #   build: ./nginx
  #   networks:
  #     shared-nw:
  #   ports:
  #     - 443:443
networks:
  shared-nw:
    driver: bridge
